### ISSUE TITLE
Exercise 10.10

### ISSUE THREAD

**Issue by humandb** [fpinscala/fpinscala#372]
This is your implementation for the `WC` monad

```
  val wcMonoid: Monoid[WC] = new Monoid[WC] {
    // The empty result, where we haven't seen any characters yet.
    val zero = Stub("")

    def op(a: WC, b: WC) = (a, b) match {
      case (Stub(c), Stub(d)) => Stub(c + d)
      case (Stub(c), Part(l, w, r)) => Part(c + l, w, r)
      case (Part(l, w, r), Stub(c)) => Part(l, w, r + c)
      case (Part(l1, w1, r1), Part(l2, w2, r2)) =>
        Part(l1, w1 + (if ((r1 + l2).isEmpty) 0 else 1) + w2, r2)
    }
  }
```

I don't think the first case is correct. You could have the following two `Stub`s, `Stub("hello world")`, `Stub("hello world")`, and the result should be `Part("hello", 1, "world")` rather than `Stub("hello worldhello world")`. Am I missing something?

**Comment by humandb** [comment]
BTW, thanks a lot for writing the book, I am enjoying it quite a lot, :)

**Comment by runarorama** [comment]
The issue is really that `String` is "too large" for the `Stub` case. We
really want a "String that doesn't contain spaces" type here.

The right thing to do would be to make the constructors of Part and Stub
private, and make the `wc` method in `count` the only constructor of WCs:

https://github.com/fpinscala/fpinscala/blob/master/answers/src/main/scala/fpinscala/monoids/Monoid.scala#L171
