### ISSUE TITLE
Exercise 3.22 solution won't work for lists of different lengths

### ISSUE THREAD

**Issue by hedleyproctor** [fpinscala/fpinscala#437]
The suggested solution for exercise 3.22 to add the elements of two lists and create a new list is:

  def addPairwise(a: List[Int], b: List[Int]): List[Int] = (a,b) match {
    case (Nil, _) => Nil
    case (_, Nil) => Nil
    case (Cons(h1,t1), Cons(h2,t2)) => Cons(h1+h2, addPairwise(t1,t2))
  }

However, for lists of different lengths, this will truncate the end of the longer list. e.g. adding List(1,2,3) to List(4,5,6,7) will produce List(5,7,9) whereas I think List(5,7,9,7) would be a more intuitive response? e.g. an implementation like

  def addPairwise(a: List[Int], b: List[Int]): List[Int] = (a,b) match {
    case (Nil, l) => l
    case (l, Nil) => l
    case (Cons(h1,t1), Cons(h2,t2)) => Cons(h1+h2, addPairwise(t1,t2))
  }

Is that a more intuitive function?

**Comment by runarorama** [comment]
It's not really important pedagogically how you handle lists of differing lengths--the purpose of the exercise is really just to get practice writing recursive functions over lists. But it's good that you're thinking about it and considering various solutions. You should stick with the solution that you think makes the most sense.

Your solution could be seen as padding the shorter list with zeroes, which is one possibility. But consider what happens when we generalize:

``` scala
def zipWith[A,B,C](as: List[A], bs: List[B])(f: (A, B) => C): List[C]
```

Now the lists aren't necessarily of the same type and it's not clear what it means to pad with zeroes. Skipping ahead to chapter 10, we could use a monoid:

``` scala
def zipWith[A,B,C:Monoid](as: List[A], bs: List[B])(f: A => C, g: B => C): List[C]
```

Or we could keep track of the padding using a data structure `These` so that we delegate the decision of how to handle it, to a later step.

``` scala
sealed trait These[A,B]
case class This[A,B](a: A) extends These[A,B]
case class That[A,B](b: B) extends These[A,B]
case class Both[A,B](a: A, b: B) extends These[A,B]

def alignWith[A,B,C](as: List[A], bs: List[B])(f: These[A,B] => C): List[C] =
  (as, bs) match {
    case (xs, Nil) => xs.map(x => f(This[A,B](x)))
    case (Nil, xs) => xs.map(x => f(That[A,B](x)))
    case (Cons(h1,t1), Cons(h2,t2)) =>
      Cons(f(Both(h1, h2)), alignWith(t1, t2)(f))
  }
```

This last solution is detailed in an old blog post by my co-author Paul:
http://pchiusano.blogspot.com/2010/06/alignable-functors-typeclass-for-zippy.html

**Comment by hedleyproctor** [comment]
Good info, thank you.
