### ISSUE TITLE
Exercise 4.1 won't compile | Scala 2.11.7

### ISSUE THREAD

**Issue by fbiville** [fpinscala/fpinscala#445]
I just removed all the other methods.
This is the "official" solution for `map`:

```scala
sealed trait Option[+A] {
	def map[B](f: A => B): Option[B] = this match {
		case None => None
		case Some(a) => Some(f(a))
	}
}
case class Some[+A](get: A) extends Option[A]
case object None extends Option[Nothing]
```

This is what Scala REPL outputs when loading the equivalent file:

```
Loading [...]/scalafp_4.01.scala...
<console>:12: error: pattern type is incompatible with expected type;
 found   : None.type
 required: Option[A]
       		case None => None
                     ^
<console>:12: error: type mismatch;
 found   : None.type
 required: Option[B]
       		case None => None
                             ^
<console>:13: error: constructor cannot be instantiated to expected type;
 found   : Some[A(in class Some)]
 required: Option[A(in trait Option)]
       		case Some(a) => Some(f(a))
                     ^
<console>:13: error: type mismatch;
 found   : Some[B]
 required: Option[B]
       		case Some(a) => Some(f(a))
                                    ^
<console>:10: error: illegal inheritance from sealed class Option
       case class Some[+A](get: A) extends Option[A]
                                           ^
<console>:10: error: illegal inheritance from sealed class Option
       case object None extends Option[Nothing]
                                ^
```

Am I missing something here?

**Comment by fbiville** [comment]
I tried also by adding the import just like [here](https://github.com/fpinscala/fpinscala/blob/master/answers/src/main/scala/fpinscala/errorhandling/Option.scala) and add imports to hide the standard Option, it still fails similarly.

**Comment by runarorama** [comment]
When you load this in the REPL, Scala compiles one expression at a time. In `None => None`, the type of `None` is `scala.Option[Nothing]`, from Scala's standard library, because your `case object None` hasn't yet been created. If you want to do this in the REPL, you should `:paste` it, or put the whole data type in an `object`.

**Comment by fbiville** [comment]
Thx :)

**Comment by manuel-uberti** [comment]
Sorry to bring up an issue closed a year ago, but is there any chance to get an updated solutions for this exercise? I am getting the error with `2.11.8`.

**Comment by gxof** [comment]
Hi @manuel-uberti ,
Maybe you have found the issue?

The problem was the masking of scala.Some, in the import.

In the exercises the import is 
`import scala.{Option => _, Some => _, Either => _, _}`

where, in the answer it is:
`import scala.{Option => _, Either => _, _}`

The answers methods that reference Some seem to actually reference scala.Some and not the one that we are implementing.

Adding  Some => _ to the import fix it all. Nothing wrong with the version.

**Comment by codeslubber** [comment]
Out of curiosity why is this still not fixed?? By adding Some to the import it did fix the compile errors. Thanks @gxof!
