### ISSUE TITLE
Question on Code Style 2.1 Fib Function

### ISSUE THREAD

**Issue by ZircXes** [fpinscala/fpinscala#579]
The book talks about using an inner function (which is comparable with the solution provided). I'd like to better understand why it is better form/style/coding practice to use the inner loop function as opposed to defining as below:

    // Exercise 2.1 Recursive Function
    def Fib(NthNumber: Int): Int = {
      if (NthNumber <= 1) NthNumber
      else Fib(NthNumber - 1) + Fib(NthNumber - 2)
    }

Thanks! It is been awhile since I've coded so I appreciate any help or guidance provided as I just popped up Scala for the first time today.

For reference, the answer key shows:
    
    def fib(n: Int): Int = {
      @annotation.tailrec
      def loop(n: Int, prev: Int, cur: Int): Int =
        if (n == 0) prev 
        else loop(n - 1, cur, prev + cur)
    loop(n, 0, 1)
    }

**Comment by falconetpt** [comment]
Hey there,

first point the inner function exists for you in order to hide some implementation details from your callers, when there are some parameters you don't need to show them, and that method only makes sense in the context of that function, you might have seen similar things in java where you call a public method that is just a proxy to a private one, scala just makes this a lot better letting you place those methods inside and encapsulated in that function

Also in the book the use of tailrec = tail recursion is made in order to avoid stackoverflow (making so many calls into the stack by creating new functions that it runs out of space), what the compiler does in the book case is to transform a recursive function into an iterative one (avoiding that problem), for that you need to create a variable which will be folded at the end, leading the compiler to optimize it automaticaly.

So looking at what you need for the compiler to do this optimization, you can see that you don't want your consumers to be passing thise values, because you don't want that logic to leak, so you hide that function definition inside the other one :)

Take for instance this approach:

def fibonaci(n: Int): Int = {
  @tailrec
  def fibonaci(previous: Int, current: Int, remaining: Int, result:
Int): Int = {
    if (remaining <= 0) {
      result
    } else {
      val fibonaciResult = current + previous
      fibonaci(current, fibonaciResult, remaining-1, fibonaciResult)
    }
  }

  fibonaci(0, 1, n, 0)
}

In which i am getting the nth fibonaci result as well

What is the difference ? i call the fibonacci from the outside exactly the
same, but inside the function i modify it in order to make tail recursion
possible :)

Makes sense to you now ?

**Comment by ZircXes** [comment]
Thanks you @falconetpt for responding so quickly and helping me to better understand. This guidance was really helpful!
